const screens=[...document.querySelectorAll('.screen')];
const $=s=>document.querySelector(s);
let teamCount=2,teams=[],current=0,qIndex=0,soundOn=true,locked=false;

const questions=[
 {round:1,type:'¿MCM O MCD?',text:'Dos luces parpadean cada 6 y 8 segundos. ¿Qué herramienta permite saber cuándo coinciden?',nums:['6 s','8 s'],options:['MCM','MCD','Resta','División'],answer:0,why:'Buscamos cuándo dos ciclos vuelven a coincidir: usamos el MCM.',tip:'Si algo vuelve a coincidir, piensa en múltiplos.'},
 {round:1,type:'¿MCM O MCD?',text:'Hay 24 jugos y 36 sándwiches. Se harán paquetes iguales sin que sobre nada. ¿Qué herramienta usamos?',nums:['24','36'],options:['MCM','MCD','Suma','Multiplicación'],answer:1,why:'Buscamos el mayor número de grupos iguales sin sobrantes: usamos el MCD.',tip:'Repartir en grupos iguales sin sobrantes apunta al MCD.'},
 {round:1,type:'¿MCM O MCD?',text:'Dos autobuses salen cada 10 y 15 minutos. ¿Cuándo volverán a salir juntos?',nums:['10 min','15 min'],options:['MCM','MCD','Promedio','Resta'],answer:0,why:'La palabra «volverán» indica una coincidencia futura; corresponde al MCM.',tip:'Los ciclos y las coincidencias se resuelven con MCM.'},
 {round:2,type:'CALCULA EL MCM',text:'Activa el portal: encuentra el mínimo común múltiplo.',nums:['8','12'],options:['16','20','24','48'],answer:2,why:'Múltiplos de 8: 8, 16, 24. De 12: 12, 24. El primero en común es 24.',tip:'Escribe múltiplos hasta encontrar el primero que se repita.'},
 {round:2,type:'CALCULA EL MCD',text:'Encuentra el mayor divisor que comparten estos números.',nums:['18','30'],options:['3','6','9','12'],answer:1,why:'Los divisores comunes son 1, 2, 3 y 6; el mayor es 6.',tip:'Lista divisores y elige el común más grande.'},
 {round:2,type:'CALCULA EL MCM',text:'¿Cuál es la primera estación común de ambas secuencias?',nums:['9','12'],options:['18','24','36','108'],answer:2,why:'36 es el menor número divisible entre 9 y entre 12.',tip:'El MCM debe ser múltiplo de todos los números.'},
 {round:3,type:'DESAFÍO FINAL',text:'Ana entrena cada 4 días y Luis cada 6. Si hoy entrenaron juntos, ¿en cuántos días coinciden?',nums:['4 días','6 días'],options:['8 días','10 días','12 días','24 días'],answer:2,why:'MCM(4, 6) = 12. Volverán a coincidir dentro de 12 días.',tip:'Coincidencia de actividades periódicas = MCM.'},
 {round:3,type:'DESAFÍO FINAL',text:'Se acomodan 42 lápices rojos y 56 azules en el mayor número de cajas iguales. ¿Cuántas cajas?',nums:['42','56'],options:['7 cajas','12 cajas','14 cajas','98 cajas'],answer:2,why:'MCD(42, 56) = 14. Se forman 14 cajas con 3 rojos y 4 azules cada una.',tip:'Mayor cantidad de grupos iguales sin sobrantes = MCD.'},
 {round:3,type:'DESAFÍO FINAL',text:'Una alarma suena cada 15 min y otra cada 20 min. Sonaron juntas a las 9:00. ¿A qué hora coinciden?',nums:['15 min','20 min'],options:['9:35','9:45','10:00','10:20'],answer:2,why:'MCM(15, 20) = 60 minutos. Una hora después de las 9:00 es a las 10:00.',tip:'Primero calcula el MCM; después interpreta la unidad.'}
];

function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));scrollTo({top:0,behavior:'smooth'})}
function beep(ok=true){if(!soundOn)return;const ctx=new (window.AudioContext||window.webkitAudioContext)(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=ok?620:190;g.gain.setValueAtTime(.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.25);o.start();o.stop(ctx.currentTime+.25)}
function buildNames(){const box=$('#teamNames');box.innerHTML='';const defaults=['Equipo Cian','Equipo Solar','Equipo Coral','Equipo Nova'];for(let i=0;i<teamCount;i++)box.insertAdjacentHTML('beforeend',`<label>EQUIPO ${i+1}<input maxlength="18" value="${defaults[i]}" aria-label="Nombre del equipo ${i+1}"></label>`)}
function startGame(){teams=[...document.querySelectorAll('#teamNames input')].map((el,i)=>({name:el.value.trim()||`Equipo ${i+1}`,score:0}));current=0;qIndex=0;locked=false;show('gameScreen');renderQuestion()}
function renderScores(){ $('#scoreboard').innerHTML=teams.map((t,i)=>`<div class="score-chip ${i===current?'active':''}"><span>${t.name}</span><b>${t.score}</b></div>`).join('') }
function renderQuestion(){locked=false;const q=questions[qIndex];renderScores();$('#roundLabel').textContent=`RONDA ${q.round}`;$('#progressLabel').textContent=`${qIndex+1} / ${questions.length}`;$('#progressBar').style.width=`${(qIndex+1)/questions.length*100}%`;$('#turnLabel').textContent=`TURNO: ${teams[current].name.toUpperCase()}`;$('#typeBadge').textContent=q.type;$('#questionText').textContent=q.text;$('#numberDisplay').innerHTML=q.nums.map(n=>`<span>${n}</span>`).join('');$('#answers').innerHTML=q.options.map((o,i)=>`<button class="answer-btn" data-answer="${i}"><small>${String.fromCharCode(65+i)}.</small> ${o}</button>`).join('');$('#hintText').textContent='💡 Conversen antes de elegir.';document.querySelectorAll('.answer-btn').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));const names=['Detectar la herramienta','Calcular con estrategia','Aplicar en contexto'];$('#missionName').textContent=names[q.round-1];$('#teacherTip').textContent=q.tip;[...document.querySelectorAll('#missionSteps li')].forEach((li,i)=>{li.className=i===q.round-1?'active':i<q.round-1?'done':''})}
function answer(choice){if(locked)return;locked=true;const q=questions[qIndex],correct=choice===q.answer;document.querySelectorAll('.answer-btn').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');else if(i===choice)b.classList.add('wrong')});if(correct)teams[current].score+=q.round===3?20:10;beep(correct);renderScores();const msg=document.createElement('div');msg.className=`feedback ${correct?'good':'bad'}`;msg.innerHTML=`${correct?'✓ ¡Portal activado!':'✕ Casi. La respuesta correcta está marcada.'}<br><span>${q.why}</span>`;$('#answers').after(msg);const next=document.createElement('button');next.className='primary next-btn';next.textContent=qIndex===questions.length-1?'VER RESULTADOS →':'SIGUIENTE RETO →';msg.after(next);next.focus();next.onclick=nextQuestion}
function nextQuestion(){document.querySelectorAll('.feedback,.next-btn').forEach(e=>e.remove());qIndex++;current=(current+1)%teams.length;if(qIndex>=questions.length)return finish();renderQuestion()}
function finish(){const max=Math.max(...teams.map(t=>t.score)),winners=teams.filter(t=>t.score===max);$('#winnerTitle').textContent=winners.length>1?'¡Empate estelar!':`¡${winners[0].name} conquista la galaxia!`;$('#winnerText').textContent=winners.length>1?`${winners.map(w=>w.name).join(' y ')} comparten la victoria con ${max} puntos.`:`Obtuvo ${max} puntos usando estrategias de MCM y MCD.`;$('#finalScores').innerHTML=[...teams].sort((a,b)=>b.score-a.score).map(t=>`<div class="final-score ${t.score===max?'winner':''}"><b>${t.name}</b><span>${t.score} puntos</span></div>`).join('');show('resultScreen')}

$('#startBtn').onclick=()=>{buildNames();show('setupScreen')};$('#launchBtn').onclick=startGame;$('#playAgainBtn').onclick=()=>{buildNames();show('setupScreen')};document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));document.querySelectorAll('#teamPicker button').forEach(b=>b.onclick=()=>{teamCount=+b.dataset.teams;document.querySelectorAll('#teamPicker button').forEach(x=>x.classList.toggle('selected',x===b));buildNames()});$('#howBtn').onclick=()=>{$('#modalContent').innerHTML='<h2>¿Cómo se juega?</h2><ol><li>Forma de <strong>2 a 4 equipos</strong>.</li><li>Cada equipo responde un reto por turno.</li><li>Las rondas 1 y 2 valen <strong>10 puntos</strong>; la final vale <strong>20 puntos</strong>.</li><li>Después de elegir, el juego explica la estrategia.</li></ol><p><strong>Sugerencia docente:</strong> pide que cada equipo justifique su elección antes de hacer clic.</p>';$('#modal').showModal()};$('#modalClose').onclick=()=>$('#modal').close();$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'♪':'∅';$('#soundBtn').setAttribute('aria-pressed',String(soundOn))};$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
document.addEventListener('keydown',e=>{if($('#gameScreen').classList.contains('active')&&!locked&&['1','2','3','4'].includes(e.key)){const b=document.querySelector(`[data-answer="${+e.key-1}"]`);if(b)b.click()}if(e.key==='Enter'&&document.querySelector('.next-btn'))document.querySelector('.next-btn').click()});
buildNames();
