const screens=[...document.querySelectorAll('.screen')];
const $=s=>document.querySelector(s);
let teamCount=2,teams=[],questions=[],current=0,qIndex=0,soundOn=true,locked=false,tiebreaker=false,tiedTeamIndexes=[],tiebreakTurn=0;

const questionBank=[
 {round:1,type:'RETO MATEMÁTICO',text:'Dos autobuses salen de la terminal cada 6 y 8 minutos. Si salen juntos ahora, ¿en cuántos minutos volverán a coincidir?',nums:['6 min','8 min'],options:['12 min','24 min','36 min','48 min'],answer:1,why:'MCM(6, 8) = 24. Los autobuses volverán a salir juntos dentro de 24 minutos.',tip:'Calcula el primer múltiplo que comparten ambas frecuencias.'},
 {round:1,type:'RETO MATEMÁTICO',text:'Una cooperativa tiene 24 jugos y 36 sándwiches. Quiere formar el mayor número de paquetes iguales sin que sobre nada. ¿Cuántos paquetes puede hacer?',nums:['24 jugos','36 sándwiches'],options:['6 paquetes','12 paquetes','18 paquetes','24 paquetes'],answer:1,why:'MCD(24, 36) = 12. Puede formar 12 paquetes con 2 jugos y 3 sándwiches cada uno.',tip:'Busca el mayor número que divida exactamente ambas cantidades.'},
 {round:1,type:'RETO MATEMÁTICO',text:'Dos luces parpadean cada 10 y 15 segundos. Si se encendieron juntas, ¿después de cuántos segundos coincidirán otra vez?',nums:['10 s','15 s'],options:['20 s','25 s','30 s','60 s'],answer:2,why:'MCM(10, 15) = 30. Las dos luces coincidirán nuevamente a los 30 segundos.',tip:'Escribe los múltiplos hasta encontrar el primero en común.'},
 {round:1,type:'RETO MATEMÁTICO',text:'Se tienen listones de 20 y 30 centímetros. Se cortarán en trozos iguales y lo más largos posible, sin desperdiciar material. ¿Cuánto medirá cada trozo?',nums:['20 cm','30 cm'],options:['5 cm','10 cm','15 cm','20 cm'],answer:1,why:'MCD(20, 30) = 10. Cada trozo puede medir 10 centímetros.',tip:'La medida debe dividir exactamente los dos listones.'},
 {round:1,type:'RETO MATEMÁTICO',text:'Sofía practica voleibol cada 4 días y atletismo cada 6 días. Si hoy realizó ambas actividades, ¿en cuántos días volverá a hacerlas el mismo día?',nums:['4 días','6 días'],options:['8 días','10 días','12 días','24 días'],answer:2,why:'MCM(4, 6) = 12. Sofía volverá a practicar ambas actividades el mismo día dentro de 12 días.',tip:'Busca la primera coincidencia entre los dos ciclos.'},
 {round:1,type:'RETO MATEMÁTICO',text:'Hay 18 cuentas rojas y 27 azules para hacer el mayor número de pulseras iguales sin que sobre ninguna. ¿Cuántas pulseras se pueden elaborar?',nums:['18 rojas','27 azules'],options:['3 pulseras','6 pulseras','9 pulseras','12 pulseras'],answer:2,why:'MCD(18, 27) = 9. Se elaboran 9 pulseras con 2 cuentas rojas y 3 azules cada una.',tip:'El número de pulseras debe dividir las dos cantidades sin residuo.'},

 {round:2,type:'RETO MATEMÁTICO',text:'En una escuela suena una campana cada 12 minutos y otra cada 18 minutos. Si sonaron juntas a las 8:00, ¿cuántos minutos pasarán para que coincidan?',nums:['12 min','18 min'],options:['24 min','30 min','36 min','72 min'],answer:2,why:'MCM(12, 18) = 36. Las campanas volverán a sonar juntas 36 minutos después.',tip:'Puedes usar múltiplos o factorización prima.'},
 {round:2,type:'RETO MATEMÁTICO',text:'Se repartirán 42 lápices y 56 plumas en el mayor número de paquetes idénticos, sin sobrantes. ¿Cuántos paquetes se formarán?',nums:['42 lápices','56 plumas'],options:['7 paquetes','12 paquetes','14 paquetes','28 paquetes'],answer:2,why:'MCD(42, 56) = 14. Cada paquete tendrá 3 lápices y 4 plumas.',tip:'Comprueba que el número de paquetes divida ambas cantidades.'},
 {round:2,type:'RETO MATEMÁTICO',text:'Dos rutas de recolección pasan por una comunidad cada 14 y 21 días. Si hoy coincidieron, ¿en cuántos días volverán a pasar el mismo día?',nums:['14 días','21 días'],options:['28 días','35 días','42 días','84 días'],answer:2,why:'MCM(14, 21) = 42. Las dos rutas volverán a coincidir dentro de 42 días.',tip:'Busca la menor cantidad de días que sea múltiplo de ambos periodos.'},
 {round:2,type:'RETO MATEMÁTICO',text:'Una panadería tiene 48 galletas y 60 chocolates. Desea preparar el mayor número de bolsas iguales sin que sobre nada. ¿Cuántas bolsas puede preparar?',nums:['48 galletas','60 chocolates'],options:['6 bolsas','10 bolsas','12 bolsas','20 bolsas'],answer:2,why:'MCD(48, 60) = 12. Cada bolsa tendrá 4 galletas y 5 chocolates.',tip:'El resultado debe dividir exactamente las dos cantidades.'},
 {round:2,type:'RETO MATEMÁTICO',text:'Tres aspersores se activan cada 8, 12 y 20 minutos. Si se activaron juntos, ¿cuántos minutos tardarán en coincidir nuevamente?',nums:['8 min','12 min','20 min'],options:['40 min','60 min','120 min','240 min'],answer:2,why:'MCM(8, 12, 20) = 120. Los tres aspersores volverán a activarse juntos en 120 minutos.',tip:'Organiza los múltiplos o factores de las tres cantidades.'},
 {round:2,type:'RETO MATEMÁTICO',text:'La biblioteca recibió 72 cuadernos y 90 lápices. Se harán el mayor número de paquetes iguales para distintos salones. ¿Cuántos paquetes se pueden formar?',nums:['72 cuadernos','90 lápices'],options:['9 paquetes','12 paquetes','18 paquetes','36 paquetes'],answer:2,why:'MCD(72, 90) = 18. Cada paquete tendrá 4 cuadernos y 5 lápices.',tip:'Busca el divisor común más grande de ambos números.'},

 {round:3,type:'DESAFÍO FINAL',text:'Tres corredores completan una vuelta cada 6, 8 y 12 minutos. Si parten juntos, ¿en cuántos minutos volverán a coincidir en la salida?',nums:['6 min','8 min','12 min'],options:['18 min','24 min','36 min','48 min'],answer:1,why:'MCM(6, 8, 12) = 24. Los tres corredores coincidirán en la salida después de 24 minutos.',tip:'El resultado debe ser múltiplo de las tres duraciones.'},
 {round:3,type:'DESAFÍO FINAL',text:'Para una jornada escolar hay 84 banderas rojas, 126 blancas y 210 verdes. Se quiere formar el mayor número de paquetes iguales sin sobrantes. ¿Cuántos paquetes se harán?',nums:['84 rojas','126 blancas','210 verdes'],options:['21 paquetes','28 paquetes','42 paquetes','84 paquetes'],answer:2,why:'MCD(84, 126, 210) = 42. Cada paquete tendrá 2 rojas, 3 blancas y 5 verdes.',tip:'Encuentra el mayor divisor que compartan las tres cantidades.'},
 {round:3,type:'DESAFÍO FINAL',text:'Tres alarmas se activan cada 15, 20 y 30 minutos. Si sonaron juntas a las 9:00, ¿a qué hora volverán a coincidir?',nums:['15 min','20 min','30 min'],options:['9:30','9:45','10:00','10:30'],answer:2,why:'MCM(15, 20, 30) = 60 minutos. Sesenta minutos después de las 9:00 son las 10:00.',tip:'Primero calcula el tiempo y después conviértelo en la hora solicitada.'},
 {round:3,type:'DESAFÍO FINAL',text:'Un patio rectangular de 96 por 120 metros se cubrirá con losetas cuadradas iguales, tan grandes como sea posible y sin recortes. ¿Cuánto medirá el lado de cada loseta?',nums:['96 m','120 m'],options:['12 m','18 m','24 m','30 m'],answer:2,why:'MCD(96, 120) = 24. Las losetas cuadradas más grandes tendrán 24 metros por lado.',tip:'La medida del lado debe dividir exactamente el largo y el ancho.'},
 {round:3,type:'DESAFÍO FINAL',text:'Tres satélites pasan sobre una estación cada 18, 24 y 30 horas. Si hoy coincidieron, ¿cuántas horas tardarán en coincidir nuevamente?',nums:['18 h','24 h','30 h'],options:['120 h','180 h','240 h','360 h'],answer:3,why:'MCM(18, 24, 30) = 360. Los tres satélites volverán a coincidir después de 360 horas.',tip:'Usa factorización prima para controlar los tres ciclos.'},
 {round:3,type:'DESAFÍO FINAL',text:'Se tienen 108 manzanas, 144 peras y 180 naranjas para armar el mayor número de canastas iguales sin sobrantes. ¿Cuántas canastas se pueden preparar?',nums:['108 manzanas','144 peras','180 naranjas'],options:['18 canastas','24 canastas','36 canastas','72 canastas'],answer:2,why:'MCD(108, 144, 180) = 36. Cada canasta tendrá 3 manzanas, 4 peras y 5 naranjas.',tip:'El número de canastas debe dividir exactamente las tres cantidades.'}
];

function shuffle(list){
 const copy=[...list];
 for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}
 return copy;
}
function prepareQuestions(){
 questions=[1,2,3].flatMap(round=>shuffle(questionBank.filter(q=>q.round===round)).slice(0,3)).map(q=>{
  const choices=shuffle(q.options.map((text,index)=>({text,correct:index===q.answer})));
  return {...q,options:choices.map(c=>c.text),answer:choices.findIndex(c=>c.correct)};
 });
}
function randomQuestion(){
 const q=shuffle(questionBank.filter(item=>item.round>1))[0];
 const choices=shuffle(q.options.map((text,index)=>({text,correct:index===q.answer})));
 return {...q,round:4,type:'MUERTE SÚBITA',options:choices.map(c=>c.text),answer:choices.findIndex(c=>c.correct)};
}

function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));scrollTo({top:0,behavior:'smooth'})}
function beep(ok=true){if(!soundOn)return;const ctx=new (window.AudioContext||window.webkitAudioContext)(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=ok?620:190;g.gain.setValueAtTime(.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.25);o.start();o.stop(ctx.currentTime+.25)}
function buildNames(){const box=$('#teamNames');box.innerHTML='';const defaults=['Equipo Cian','Equipo Solar','Equipo Coral','Equipo Nova'];for(let i=0;i<teamCount;i++)box.insertAdjacentHTML('beforeend',`<label>EQUIPO ${i+1}<input maxlength="18" value="${defaults[i]}" aria-label="Nombre del equipo ${i+1}"></label>`)}
function startGame(){teams=[...document.querySelectorAll('#teamNames input')].map((el,i)=>({name:el.value.trim()||`Equipo ${i+1}`,score:0}));prepareQuestions();current=0;qIndex=0;locked=false;tiebreaker=false;show('gameScreen');renderQuestion()}
function renderScores(){ $('#scoreboard').innerHTML=teams.map((t,i)=>`<div class="score-chip ${i===current?'active':''}"><span>${t.name}</span><b>${t.score}</b></div>`).join('') }
function renderQuestion(){locked=false;const q=questions[qIndex];renderScores();$('#roundLabel').textContent=tiebreaker?'DESEMPATE':`RONDA ${q.round}`;$('#progressLabel').textContent=tiebreaker?'MUERTE SÚBITA':`${qIndex+1} / ${questions.length}`;$('#progressBar').style.width=tiebreaker?'100%':`${(qIndex+1)/questions.length*100}%`;$('#turnLabel').textContent=`TURNO: ${teams[current].name.toUpperCase()}`;$('#typeBadge').textContent=q.type;$('#questionText').textContent=q.text;$('#numberDisplay').innerHTML=q.nums.map(n=>`<span>${n}</span>`).join('');$('#answers').innerHTML=q.options.map((o,i)=>`<button class="answer-btn" data-answer="${i}"><small>${String.fromCharCode(65+i)}.</small> ${o}</button>`).join('');$('#hintText').textContent=tiebreaker?'⚡ El primer equipo que acierte gana.':'💡 Conversen antes de elegir.';document.querySelectorAll('.answer-btn').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));const names=['Detectar la herramienta','Calcular con estrategia','Aplicar en contexto'];const neutralTips=['Identifiquen los datos y calculen antes de revisar las opciones.','Pueden usar listas de múltiplos, divisores o factorización prima.','Organicen las cantidades, calculen y después interpreten la unidad solicitada.'];$('#missionName').textContent=tiebreaker?'Romper el empate':names[q.round-1];$('#teacherTip').textContent=tiebreaker?'Revisen los datos y acuerden una respuesta antes de elegir.':neutralTips[q.round-1];[...document.querySelectorAll('#missionSteps li')].forEach((li,i)=>{li.className=tiebreaker?'done':i===q.round-1?'active':i<q.round-1?'done':''})}
function answer(choice){if(locked)return;locked=true;const q=questions[qIndex],correct=choice===q.answer;document.querySelectorAll('.answer-btn').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');else if(i===choice)b.classList.add('wrong')});if(correct&&!tiebreaker)teams[current].score+=q.round===3?20:10;beep(correct);renderScores();const msg=document.createElement('div');msg.className=`feedback ${correct?'good':'bad'}`;const headline=tiebreaker&&correct?'✓ ¡Desempate resuelto!':correct?'✓ ¡Portal activado!':'✕ Casi. La respuesta correcta está marcada.';msg.innerHTML=`${headline}<br><span>${q.why}</span>`;$('#answers').after(msg);const next=document.createElement('button');next.className='primary next-btn';if(tiebreaker){next.textContent=correct?'VER AL EQUIPO GANADOR →':'SIGUIENTE EQUIPO →';next.onclick=correct?()=>showWinner(teams[current]):nextTiebreakTurn}else{next.textContent=qIndex===questions.length-1?'VER RESULTADOS →':'SIGUIENTE RETO →';next.onclick=nextQuestion}msg.after(next);next.focus()}
function nextQuestion(){document.querySelectorAll('.feedback,.next-btn').forEach(e=>e.remove());qIndex++;current=(current+1)%teams.length;if(qIndex>=questions.length)return finish();renderQuestion()}
function finish(){const max=Math.max(...teams.map(t=>t.score)),winners=teams.filter(t=>t.score===max);if(winners.length>1)return announceTiebreaker(winners);showWinner(winners[0])}
function announceTiebreaker(winners){const names=winners.map(team=>team.name);$('#tieMessage').textContent=`${names.join(names.length===2?' y ':', ')} terminaron con ${winners[0].score} puntos. Es hora de la muerte súbita.`;const modal=$('#tieModal');modal.showModal();$('#startTiebreakBtn').onclick=()=>{modal.close();startTiebreaker(winners)};$('#startTiebreakBtn').focus()}
function startTiebreaker(winners){tiebreaker=true;tiedTeamIndexes=shuffle(winners.map(team=>teams.indexOf(team)));tiebreakTurn=0;current=tiedTeamIndexes[0];questions=[randomQuestion()];qIndex=0;show('gameScreen');renderQuestion()}
function nextTiebreakTurn(){document.querySelectorAll('.feedback,.next-btn').forEach(e=>e.remove());tiebreakTurn=(tiebreakTurn+1)%tiedTeamIndexes.length;current=tiedTeamIndexes[tiebreakTurn];questions=[randomQuestion()];qIndex=0;renderQuestion()}
function showWinner(winner){tiebreaker=false;const max=Math.max(...teams.map(t=>t.score));$('#winnerTitle').textContent=`¡${winner.name} conquista la galaxia!`;$('#winnerText').textContent=`Terminó la misión con ${winner.score} puntos y resolvió el desafío final.`;$('#finalScores').innerHTML=[...teams].sort((a,b)=>b.score-a.score).map(t=>`<div class="final-score ${t===winner?'winner':''}"><b>${t.name}</b><span>${t.score} puntos</span></div>`).join('');show('resultScreen')}

$('#startBtn').onclick=()=>{buildNames();show('setupScreen')};$('#launchBtn').onclick=startGame;$('#playAgainBtn').onclick=()=>{buildNames();show('setupScreen')};document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));document.querySelectorAll('#teamPicker button').forEach(b=>b.onclick=()=>{teamCount=+b.dataset.teams;document.querySelectorAll('#teamPicker button').forEach(x=>x.classList.toggle('selected',x===b));buildNames()});$('#howBtn').onclick=()=>{$('#modalContent').innerHTML='<h2>¿Cómo se juega?</h2><ol><li>Forma de <strong>2 a 4 equipos</strong>.</li><li>Cada equipo responde un reto por turno.</li><li>Las rondas 1 y 2 valen <strong>10 puntos</strong>; la final vale <strong>20 puntos</strong>.</li><li>Después de elegir, el juego explica la estrategia.</li></ol><p><strong>Sugerencia docente:</strong> pide que cada equipo justifique su elección antes de hacer clic.</p>';$('#modal').showModal()};$('#modalClose').onclick=()=>$('#modal').close();$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'♪':'∅';$('#soundBtn').setAttribute('aria-pressed',String(soundOn))};$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
document.addEventListener('keydown',e=>{if($('#gameScreen').classList.contains('active')&&!locked&&['1','2','3','4'].includes(e.key)){const b=document.querySelector(`[data-answer="${+e.key-1}"]`);if(b)b.click()}if(e.key==='Enter'&&document.querySelector('.next-btn'))document.querySelector('.next-btn').click()});
buildNames();
